name: Deploy

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
        default: 'v1.0.0'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - run: echo "Déploiement de l'image ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ github.event.inputs.version }} sur production..."
      - run: echo "Secret APP_SECRET : ${{ secrets.APP_SECRET }}"
